import yaml

strategy_config_file = "configs/strategyconfigs.yml"

strats = [
    {
        "index": {"Ticker": "NIFTY", "Expiry": "28SEP", "Init": 19800, "Adjustment" : 2},
        "strategy": "ThetaGamma",
        "name" : "nif2",
        "strategy_args": {
            "refIV": 0.10,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "size",
            "size_target" : 12000,
            "position_size_limit" : 36000,
            # "target" : "theta",
            # "theta_target" : 100000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "BANKNIFTY", "Expiry": "28SEP", "Init": 45300, "Adjustment" : 2},
        "strategy": "ThetaGamma",
        "name" : "bnf2",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "size",
            "size_target" : 4800,
            "position_size_limit" : 14400,
            # "target" : "theta",
            # "theta_target" : 25000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "FINNIFTY", "Expiry": "26SEP", "Init": 20300, "Adjustment" : 2},
        "strategy": "ThetaGamma",
        "name" : "finn2",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 240,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "size",
            "size_target" : 9600,
            "position_size_limit" : 28800,
            # "target" : "theta",
            # "theta_target" : 30000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "MIDCPNIFTY", "Expiry": "25SEP", "Init": 9150, "Adjustment" : 2},  
        "strategy": "ThetaGamma",
        "name" : "midc2",
        "strategy_args": {
            "refIV": 0.15,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "size",
            "size_target" : 4200,
            "position_size_limit" : 12600,
            # "target" : "theta",
            # "theta_target" : 20000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },












    {
        "index": {"Ticker": "NIFTY", "Expiry": "28SEP", "Init": 19800, "Adjustment" : 2},
        "strategy": "StraddlebyThree",
        "name" : "nif4",
        "strategy_args": {
            "refIV": 0.10,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "size",
            "size_target" : 12000,
            "position_size_limit" : 36000,
            # "target" : "theta",
            # "theta_target" : 100000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "BANKNIFTY", "Expiry": "28SEP", "Init": 45300, "Adjustment" : 2},
        "strategy": "StraddlebyThree",
        "name" : "bnf4",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "size",
            "size_target" : 4800,
            "position_size_limit" : 14400,
            # "target" : "theta",
            # "theta_target" : 25000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "FINNIFTY", "Expiry": "26SEP", "Init": 20300, "Adjustment" : 2},
        "strategy": "StraddlebyThree",
        "name" : "finn4",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 240,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "theta",
            "target" : "size",
            "size_target" : 9600,
            "position_size_limit" : 28800,
            # "theta_target" : 30000,
            # "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "MIDCPNIFTY", "Expiry": "25SEP", "Init": 9150, "Adjustment" : 2},  
        "strategy": "StraddlebyThree",
        "name" : "midc4",
        "strategy_args": {
            "refIV": 0.15,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 0.5,
            "target" : "size",
            "size_target" : 4200,
            "position_size_limit" : 12600,
            # "target" : "theta",
            # "theta_target" : 20000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },


    










    {
        "index": {"Ticker": "NIFTY", "Expiry": "28SEP", "Init": 19800, "Adjustment" : 2},
        "strategy": "RollingStraddle",
        "name" : "nif5",
        "strategy_args": {
            "refIV": 0.10,
            "demand": 3000,
            "wings": 2,
            "IVCalc": "Reference",  
            "hedge_amount": 1,
            "position_size_limit" : 36000,
            "target" : "theta",
            "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:20:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 60,
            "destruction_lots_per_cycle" : 60,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "BANKNIFTY", "Expiry": "28SEP", "Init": 45300, "Adjustment" : 2},
        "strategy": "RollingStraddle",
        "name" : "bnf5",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 1200,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "position_size_limit" : 14400,
            "target" : "theta",
            "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:20:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 100,
            "destruction_lots_per_cycle" : 100,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "FINNIFTY", "Expiry": "26SEP", "Init": 20300, "Adjustment" : 2},  
        "strategy": "RollingStraddle",
        "name" : "finn5",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 2400,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "position_size_limit" : 28800,
            "target" : "theta",
            "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:20:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 75,
            "destruction_lots_per_cycle" : 75,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "MIDCPNIFTY", "Expiry": "25SEP", "Init": 9150, "Adjustment" : 2},  
        "strategy": "RollingStraddle",
        "name" : "midc5",
        "strategy_args": {
            "refIV": 0.15,
            "demand": 1050,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "position_size_limit" : 12600,
            "target" : "theta",
            "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:20:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },












    
    
    {
        "index": {"Ticker": "NIFTY", "Expiry": "28SEP", "Init": 19800, "Adjustment" : 2},
        "strategy": "smartstraddle",
        "name" : "nif3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 6000,
            "tranche_2_target" : 12000,
            "tranche_3_target" : 18000,
            "expected_close" : 175,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 12000,
            "position_size_limit_2" : 18000,
            "position_size_limit_3" : 24000,
            "refIV": 0.10,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",  
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 100000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "BANKNIFTY", "Expiry": "28SEP", "Init": 45300, "Adjustment" : 2},
        "strategy": "smartstraddle",
        "name" : "bnf3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 2400,
            "tranche_2_target" : 4800,
            "tranche_3_target" : 7200,
            "expected_close" : 540,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 4800,
            "position_size_limit_2" : 7200,
            "position_size_limit_3" : 9600,
            "refIV": 0.13,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 25000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "FINNIFTY", "Expiry": "26SEP", "Init": 20300, "Adjustment" : 2},  
        "strategy": "smartstraddle",
        "name" : "finn3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 4800,
            "tranche_2_target" : 9600,
            "tranche_3_target" : 14400,
            "expected_close" : 155,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 9600,
            "position_size_limit_2" : 14400,
            "position_size_limit_3" : 19200,
            "refIV": 0.13,
            "demand": 240,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 30000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "MIDCPNIFTY", "Expiry": "25SEP", "Init": 9150, "Adjustment" : 2},  
        "strategy": "smartstraddle",
        "name" : "midc3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 2100,
            "tranche_2_target" : 4200,
            "tranche_3_target" : 6300,
            "expected_close" : 60,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 4200,
            "position_size_limit_2" : 6300,
            "position_size_limit_3" : 8400,
            "refIV": 0.15,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 20000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },







    {
        "index": {"Ticker": "NIFTY", "Expiry": "28SEP", "Init": 19800, "Adjustment" : 2},
        "strategy": "SmartStraddleNoExit",
        "name" : "nif3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 6000,
            "tranche_2_target" : 12000,
            "tranche_3_target" : 18000,
            "expected_close" : 175,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 12000,
            "position_size_limit_2" : 18000,
            "position_size_limit_3" : 24000,
            "refIV": 0.10,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",  
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 100000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "BANKNIFTY", "Expiry": "28SEP", "Init": 45300, "Adjustment" : 2},
        "strategy": "SmartStraddleNoExit",
        "name" : "bnf3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 2400,
            "tranche_2_target" : 4800,
            "tranche_3_target" : 7200,
            "expected_close" : 540,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 4800,
            "position_size_limit_2" : 7200,
            "position_size_limit_3" : 9600,
            "refIV": 0.13,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 25000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "FINNIFTY", "Expiry": "26SEP", "Init": 20300, "Adjustment" : 2},  
        "strategy": "SmartStraddleNoExit",
        "name" : "finn3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 4800,
            "tranche_2_target" : 9600,
            "tranche_3_target" : 14400,
            "expected_close" : 155,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 9600,
            "position_size_limit_2" : 14400,
            "position_size_limit_3" : 19200,
            "refIV": 0.13,
            "demand": 240,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 30000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },
    {
        "index": {"Ticker": "MIDCPNIFTY", "Expiry": "25SEP", "Init": 9150, "Adjustment" : 2},  
        "strategy": "SmartStraddleNoExit",
        "name" : "midc3",
        "strategy_args": {
            "tranche1" : 0.0105,
            "tranche2" : 0.0140,
            "tranche3" : 0.0195,
            "tranche_0_target" : 0,
            "tranche_1_target" : 2100,
            "tranche_2_target" : 4200,
            "tranche_3_target" : 6300,
            "expected_close" : 60,
            "position_size_limit_0" : 0,
            "position_size_limit_1" : 4200,
            "position_size_limit_2" : 6300,
            "position_size_limit_3" : 8400,
            "refIV": 0.15,
            "demand": 150,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "theta",
            "theta_target" : 20000,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : False,
        },
    },








    {
        "index": {"Ticker": "NIFTY", "Expiry": "28SEP", "Init": 19800, "Adjustment" : 2},
        "strategy": "StraddlebyThree",
        "name" : "nif",
        "strategy_args": {
            "refIV": 0.10,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",  
            "hedge_amount": 1,
            "target" : "size",
            "size_target" : 0,
            "position_size_limit" : 36000,
            # "target" : "theta",
            # "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : True,
            "existing_pf" : {'19750PE': -3000, '19800CE': -3000, '19250PE': 3000, '20300CE': 3000},
            'existing_pf_value' : -524550,
        },
    },
    {
        "index": {"Ticker": "BANKNIFTY", "Expiry": "28SEP", "Init": 45300, "Adjustment" : 2},
        "strategy": "StraddlebyThree",
        "name" : "bnf6",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "size",
            "size_target" : 0,
            "position_size_limit" : 14400,
            # "target" : "theta",
            # "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : True,
            "existing_pf" : {'44700PE': -1200, '44800CE': -1200, '43300PE': 1200, '46200CE': 1200},
            'existing_pf_value' : -633360,
        },
    },
    {
        "index": {"Ticker": "FINNIFTY", "Expiry": "26SEP", "Init": 20300, "Adjustment" : 2},  
        "strategy": "StraddlebyThree",
        "name" : "finn6",
        "strategy_args": {
            "refIV": 0.13,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "size",
            "size_target" : 0,
            "position_size_limit" : 28800,
            # "target" : "theta",
            # "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : True,
            "existing_pf" : {'19850PE': -2400, '19850CE': -2400, '19450PE': 2400, '20250CE': 2400},
            'existing_pf_value' : -427680,
        },
    },
    {
        "index": {"Ticker": "MIDCPNIFTY", "Expiry": "25SEP", "Init": 9150, "Adjustment" : 2},  
        "strategy": "StraddlebyThree",
        "name" : "midc6",
        "strategy_args": {
            "refIV": 0.15,
            "demand": 250,
            "wings": 2,
            "IVCalc": "Reference",
            "hedge_amount": 1,
            "target" : "size",
            "size_target" : 0,
            "position_size_limit" : 12600,
            # "target" : "theta",
            # "theta_target" : 0,
            "close_position" : False,
            "close_position_time" : "15:00:00",
            "decrease_position" : False,
            "construction_lots_per_cycle" : 10,
            "destruction_lots_per_cycle" : 10,
            "quantity_limit" : 5,
            "hedge_point_multiplier" : 1,
            "position_exists" : True,
            "existing_pf" : {'9075PE': -1050, '9075CE': -1050, '8875PE': 1050, '9275CE': 1050},
            'existing_pf_value' : -86310,
        },
    },
]


'''
25000
30000
45000
75000
100000

10000
15000
20000
37500
50000

banknifty 5000 straddles = 2cr
nifty/fin 5000 straddles = 1cr

banknifty 10,000 spreads at straddle price = 2cr 
nifty/fin 10,000 spreads at straddle price = 1cr

banknifty limit = 7.5*10,000 = 15cr
nifty/fin = 15*10,000 = 15cr


round up
tolerance

5x of begin max options
'''

f = open(strategy_config_file, "w")
strategy_configs = yaml.safe_dump(strats, f)
f.flush()
f.close()


# with open(strategy_config_file, "w") as f:
#     strategy_configs = yaml.safe_dump(strats, f)

# print(strategy_configs)
