- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 19800
    Ticker: NIFTY
  name: nif2
  strategy: ThetaGamma
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 36000
    quantity_limit: 5
    refIV: 0.1
    size_target: 12000
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 45300
    Ticker: BANKNIFTY
  name: bnf2
  strategy: ThetaGamma
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 14400
    quantity_limit: 5
    refIV: 0.13
    size_target: 4800
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 26SEP
    Init: 20300
    Ticker: FINNIFTY
  name: finn2
  strategy: ThetaGamma
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 240
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 28800
    quantity_limit: 5
    refIV: 0.13
    size_target: 9600
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 25SEP
    Init: 9150
    Ticker: MIDCPNIFTY
  name: midc2
  strategy: ThetaGamma
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 12600
    quantity_limit: 5
    refIV: 0.15
    size_target: 4200
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 19800
    Ticker: NIFTY
  name: nif4
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 36000
    quantity_limit: 5
    refIV: 0.1
    size_target: 12000
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 45300
    Ticker: BANKNIFTY
  name: bnf4
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 14400
    quantity_limit: 5
    refIV: 0.13
    size_target: 4800
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 26SEP
    Init: 20300
    Ticker: FINNIFTY
  name: finn4
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 240
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 28800
    quantity_limit: 5
    refIV: 0.13
    size_target: 9600
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 25SEP
    Init: 9150
    Ticker: MIDCPNIFTY
  name: midc4
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    hedge_amount: 0.5
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 12600
    quantity_limit: 5
    refIV: 0.15
    size_target: 4200
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 19800
    Ticker: NIFTY
  name: nif5
  strategy: RollingStraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:20:00'
    construction_lots_per_cycle: 60
    decrease_position: false
    demand: 3000
    destruction_lots_per_cycle: 60
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 36000
    quantity_limit: 5
    refIV: 0.1
    target: theta
    theta_target: 0
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 45300
    Ticker: BANKNIFTY
  name: bnf5
  strategy: RollingStraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:20:00'
    construction_lots_per_cycle: 100
    decrease_position: false
    demand: 1200
    destruction_lots_per_cycle: 100
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 14400
    quantity_limit: 5
    refIV: 0.13
    target: theta
    theta_target: 0
    wings: 2
- index:
    Adjustment: 2
    Expiry: 26SEP
    Init: 20300
    Ticker: FINNIFTY
  name: finn5
  strategy: RollingStraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:20:00'
    construction_lots_per_cycle: 75
    decrease_position: false
    demand: 2400
    destruction_lots_per_cycle: 75
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 28800
    quantity_limit: 5
    refIV: 0.13
    target: theta
    theta_target: 0
    wings: 2
- index:
    Adjustment: 2
    Expiry: 25SEP
    Init: 9150
    Ticker: MIDCPNIFTY
  name: midc5
  strategy: RollingStraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:20:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 1050
    destruction_lots_per_cycle: 10
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit: 12600
    quantity_limit: 5
    refIV: 0.15
    target: theta
    theta_target: 0
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 19800
    Ticker: NIFTY
  name: nif3
  strategy: smartstraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    expected_close: 175
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 12000
    position_size_limit_2: 18000
    position_size_limit_3: 24000
    quantity_limit: 5
    refIV: 0.1
    target: theta
    theta_target: 100000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 6000
    tranche_2_target: 12000
    tranche_3_target: 18000
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 45300
    Ticker: BANKNIFTY
  name: bnf3
  strategy: smartstraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    expected_close: 540
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 4800
    position_size_limit_2: 7200
    position_size_limit_3: 9600
    quantity_limit: 5
    refIV: 0.13
    target: theta
    theta_target: 25000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 2400
    tranche_2_target: 4800
    tranche_3_target: 7200
    wings: 2
- index:
    Adjustment: 2
    Expiry: 26SEP
    Init: 20300
    Ticker: FINNIFTY
  name: finn3
  strategy: smartstraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 240
    destruction_lots_per_cycle: 10
    expected_close: 155
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 9600
    position_size_limit_2: 14400
    position_size_limit_3: 19200
    quantity_limit: 5
    refIV: 0.13
    target: theta
    theta_target: 30000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 4800
    tranche_2_target: 9600
    tranche_3_target: 14400
    wings: 2
- index:
    Adjustment: 2
    Expiry: 25SEP
    Init: 9150
    Ticker: MIDCPNIFTY
  name: midc3
  strategy: smartstraddle
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    expected_close: 60
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 4200
    position_size_limit_2: 6300
    position_size_limit_3: 8400
    quantity_limit: 5
    refIV: 0.15
    target: theta
    theta_target: 20000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 2100
    tranche_2_target: 4200
    tranche_3_target: 6300
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 19800
    Ticker: NIFTY
  name: nif3
  strategy: SmartStraddleNoExit
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    expected_close: 175
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 12000
    position_size_limit_2: 18000
    position_size_limit_3: 24000
    quantity_limit: 5
    refIV: 0.1
    target: theta
    theta_target: 100000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 6000
    tranche_2_target: 12000
    tranche_3_target: 18000
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 45300
    Ticker: BANKNIFTY
  name: bnf3
  strategy: SmartStraddleNoExit
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    expected_close: 540
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 4800
    position_size_limit_2: 7200
    position_size_limit_3: 9600
    quantity_limit: 5
    refIV: 0.13
    target: theta
    theta_target: 25000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 2400
    tranche_2_target: 4800
    tranche_3_target: 7200
    wings: 2
- index:
    Adjustment: 2
    Expiry: 26SEP
    Init: 20300
    Ticker: FINNIFTY
  name: finn3
  strategy: SmartStraddleNoExit
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 240
    destruction_lots_per_cycle: 10
    expected_close: 155
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 9600
    position_size_limit_2: 14400
    position_size_limit_3: 19200
    quantity_limit: 5
    refIV: 0.13
    target: theta
    theta_target: 30000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 4800
    tranche_2_target: 9600
    tranche_3_target: 14400
    wings: 2
- index:
    Adjustment: 2
    Expiry: 25SEP
    Init: 9150
    Ticker: MIDCPNIFTY
  name: midc3
  strategy: SmartStraddleNoExit
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 150
    destruction_lots_per_cycle: 10
    expected_close: 60
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: false
    position_size_limit_0: 0
    position_size_limit_1: 4200
    position_size_limit_2: 6300
    position_size_limit_3: 8400
    quantity_limit: 5
    refIV: 0.15
    target: theta
    theta_target: 20000
    tranche1: 0.0105
    tranche2: 0.014
    tranche3: 0.0195
    tranche_0_target: 0
    tranche_1_target: 2100
    tranche_2_target: 4200
    tranche_3_target: 6300
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 19800
    Ticker: NIFTY
  name: nif
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    existing_pf:
      19250PE: 3000
      19750PE: -3000
      19800CE: -3000
      20300CE: 3000
    existing_pf_value: -524550
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: true
    position_size_limit: 36000
    quantity_limit: 5
    refIV: 0.1
    size_target: 0
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 28SEP
    Init: 45300
    Ticker: BANKNIFTY
  name: bnf6
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    existing_pf:
      43300PE: 1200
      44700PE: -1200
      44800CE: -1200
      46200CE: 1200
    existing_pf_value: -633360
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: true
    position_size_limit: 14400
    quantity_limit: 5
    refIV: 0.13
    size_target: 0
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 26SEP
    Init: 20300
    Ticker: FINNIFTY
  name: finn6
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    existing_pf:
      19450PE: 2400
      19850CE: -2400
      19850PE: -2400
      20250CE: 2400
    existing_pf_value: -427680
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: true
    position_size_limit: 28800
    quantity_limit: 5
    refIV: 0.13
    size_target: 0
    target: size
    wings: 2
- index:
    Adjustment: 2
    Expiry: 25SEP
    Init: 9150
    Ticker: MIDCPNIFTY
  name: midc6
  strategy: StraddlebyThree
  strategy_args:
    IVCalc: Reference
    close_position: false
    close_position_time: '15:00:00'
    construction_lots_per_cycle: 10
    decrease_position: false
    demand: 250
    destruction_lots_per_cycle: 10
    existing_pf:
      8875PE: 1050
      9075CE: -1050
      9075PE: -1050
      9275CE: 1050
    existing_pf_value: -86310
    hedge_amount: 1
    hedge_point_multiplier: 1
    position_exists: true
    position_size_limit: 12600
    quantity_limit: 5
    refIV: 0.15
    size_target: 0
    target: size
    wings: 2
